export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const ALERT = 'ALERT';
export const ALERT_DISMISS = 'ALERT_DISMISS';
export const USER_UPDATE = 'USER_UPDATE';
export const ACHIEVEMENT_LIST_UPDATE = 'ACHIEVEMENT_LIST_UPDATE';
export const ACHIEVEMENT_AWARD = 'ACHIEVEMENT_AWARD';